//
// Created by Zeno on 2016/9/11.
//

#ifndef ENCRYPTANDDECRYPT_UTIL_H
#define ENCRYPTANDDECRYPT_UTIL_H


#define LOGE(TAG,FORMAT,...) __android_log_print(ANDROID_LOG_ERROR,TAG,FORMAT,__VA_ARGS__)


#endif //ENCRYPTANDDECRYPT_UTIL_H
